DW-Final-Project/DW-Final-Project/Models/OrderItem.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DW_Final_Project.Models
{
	/// <summary>
	/// Detalhes de um item, numa determinada Ordem/Compra
	/// </summary>
	public class OrderItem
	{
		/// <summary>
		/// PK
		/// </summary>
		public int id { get; set; }


        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório")]
        [RegularExpression("[SML]{1}",
         ErrorMessage = "O {0} deve ter apenas um caracter.")]
        [Display(Name = "Tamanho")]
        public string size { get; set; }

		/// <summary>
		/// Quantidade de um item numa ordem/compra
		/// </summary>
		[Required(ErrorMessage = "A {0} é de preenchimento obrigatório")]
		[Display(Name = "Quantidade")]
        [RegularExpression("^[1-9][0-9]*",
           ErrorMessage = "A {0} tem de ser maior do que um")]
        public int quantity { get; set; }

        /// <summary>
        /// Preço total de um determinado item numa ordem/compra (totalPrice = quantidade * preco/unid
        /// </summary>
        /// <summary>
        /// Preço unitário de um produto
        /// </summary>
        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório")]
        [Display(Name = "Preço")]
        public decimal totalPrice { get; set; }

        /// <summary>
        /// Campo auxiliar de introdução do Preço de um produto
        /// </summary>
        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório")]
        [Display(Name = "Preço")]
        [RegularExpression("[0-9]+[.,]?[0-9]{1,2}",
           ErrorMessage = "No {0} só pode usar algarismos, e se desejar," +
           " duas casas decimais no final.")]
        [NotMapped]
        public string totalPriceAux { get; set; }


        /// <summary>
        /// FK Order
        /// </summary>
        [ForeignKey(nameof(order))]
		public int orderFK { get; set; }
		public Order order { get; set; }
		
		/// <summary>
		/// FK produto
		/// </summary>
		[ForeignKey(nameof(product))]
		public int productFK { get; set; }
		public Product product { get; set; }
	}
}

DW-Final-Project/DW-Final-Project/Controllers/OrderItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DW_Final_Project.Data;
using DW_Final_Project.Models;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Authorization;

namespace DW_Final_Project.Controllers
{
    [Authorize]
    public class OrderItemController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrderItemController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: OrderItem
        public async Task<IActionResult> Index()
        {
            if (!User.Identity.Name.Contains("@admin.ipt.pt"))
            {
                return NotFound();
            }
            var applicationDbContext = _context.OrderItem.Include(o => o.order).Include(o => o.product);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: OrderItem/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (!User.Identity.Name.Contains("@admin.ipt.pt"))
            {
                return NotFound();
            }
            if (id == null || _context.OrderItem == null)
            {
                return NotFound();
            }

            var orderItem = await _context.OrderItem
                .Include(o => o.order)
                .Include(o => o.product)
                .FirstOrDefaultAsync(m => m.id == id);
            if (orderItem == null)
            {
                return NotFound();
            }

            return View(orderItem);
        }

        // GET: OrderItem/Create
        public IActionResult Create()
        {
            if (!User.Identity.Name.Contains("@admin.ipt.pt"))
            {
                return NotFound();
            }
            ViewData["orderFK"] = new SelectList(_context.Order, "id", "id");
            ViewData["productFK"] = new SelectList(_context.Product, "id", "name");
            return View();
        }

        // POST: OrderItem/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("size,quantity,orderFK,productFK")] OrderItem orderItem)
        {
            if (!User.Identity.Name.Contains("@admin.ipt.pt"))
            {
                return NotFound();
            }
            ModelState.Remove("order");
            ModelState.Remove("product");
            ModelState.Remove("totalPriceAux");
            Product p = await _context.Product.FindAsync(orderItem.productFK);
            orderItem.totalPrice = p.price * orderItem.quantity;
            if (ModelState.IsValid)
            {
                _context.Add(orderItem);
                await _context.SaveChangesAsync();
                Order o = await _context.Order.FindAsync(orderItem.orderFK);
                o.price += orderItem.totalPrice;
                _context.Update(o);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["orderFK"] = new SelectList(_context.Order, "id", "id", orderItem.orderFK);
            ViewData["productFK"] = new SelectList(_context.Product, "id", "name", orderItem.productFK);
            return View(orderItem);
        }

        // GET: OrderItem/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (!User.Identity.Name.Contains("@admin.ipt.pt"))
            {
                return NotFound();
            }
            if (id == null || _context.OrderItem == null)
            {
                return NotFound();
            }

            var orderItem = await _context.OrderItem.FindAsync(id);
            if (orderItem == null)
            {
                return NotFound();
            }
            ViewData["orderFK"] = new SelectList(_context.Order, "id", "id", orderItem.orderFK);
            ViewData["productFK"] = new SelectList(_context.Product, "id", "name", orderItem.productFK);
            return View(orderItem);
        }

        // POST: OrderItem/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,size,quantity,productFK")] OrderItem orderItem)
        {
            if (!User.Identity.Name.Contains("@admin.ipt.pt"))
            {
                return NotFound();
            }
            if (id != orderItem.id)
            {
                return NotFound();
            }
            OrderItem olderItem = await _context.OrderItem.FindAsync(id);
            decimal precoApagar = olderItem.totalPrice;
            OrderItem existingOrderItem = await _context.OrderItem.FindAsync(id);
            existingOrderItem.quantity = orderItem.quantity;
            existingOrderItem.size = orderItem.size;
            existingOrderItem.orderFK = olderItem.orderFK;
            existingOrderItem.productFK = orderItem.productFK;
            existingOrderItem.quantity = orderItem.quantity;
            Product oldP = await _context.Product.FindAsync(olderItem.productFK);
            Product newP = await _context.Product.FindAsync(existingOrderItem.productFK);
            existingOrderItem.totalPrice = orderItem.quantity * newP.price;
            decimal preco = oldP.price * olderItem.quantity;
            ModelState.Remove("order");
            ModelState.Remove("product");
            ModelState.Remove("totalPriceAux");
            if (ModelState.IsValid)
            {
                try
                {
                    Order o = await _context.Order.FindAsync(existingOrderItem.orderFK);
                    o.price -= precoApagar;
                    o.price += existingOrderItem.totalPrice;
                    _context.Update(existingOrderItem);
                    await _context.SaveChangesAsync();
                    _context.Update(o);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderItemExists(orderItem.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["orderFK"] = new SelectList(_context.Order, "id", "id", orderItem.orderFK);
            ViewData["productFK"] = new SelectList(_context.Product, "id", "name", orderItem.productFK);
            return View(orderItem);
        }

        // GET: OrderItem/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (!User.Identity.Name.Contains("@admin.ipt.pt"))
            {
                return NotFound();
            }
            if (id == null || _context.OrderItem == null)
            {
                return NotFound();
            }

            var orderItem = await _context.OrderItem
                .Include(o => o.order)
                .Include(o => o.product)
                .FirstOrDefaultAsync(m => m.id == id);
            if (orderItem == null)
            {
                return NotFound();
            }

            return View(orderItem);
        }

        // POST: OrderItem/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (!User.Identity.Name.Contains("@admin.ipt.pt"))
            {
                return NotFound();
            }
            if (_context.OrderItem == null)
            {
                return Problem("Entity set 'ApplicationDbContext.OrderItem'  is null.");
            }
            var orderItem = await _context.OrderItem.FindAsync(id);
            if (orderItem != null)
            {
                _context.OrderItem.Remove(orderItem);
                Order o = await _context.Order.FindAsync(orderItem.orderFK);
                o.price -= orderItem.totalPrice;
                _context.Order.Update(o);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderItemExists(int id)
        {
            return (_context.OrderItem?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

DW-Final-Project/DW-Final-Project/Controllers/OrderItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DW_Final_Project.Data;
using DW_Final_Project.Models;

namespace DW_Final_Project.Controllers
{
    public class OrderItemsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OrderItemsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: OrderItems
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.OrderItem.Include(o => o.order).Include(o => o.product);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: OrderItems/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.OrderItem == null)
            {
                return NotFound();
            }

            var orderItem = await _context.OrderItem
                .Include(o => o.order)
                .Include(o => o.product)
                .FirstOrDefaultAsync(m => m.id == id);
            if (orderItem == null)
            {
                return NotFound();
            }

            return View(orderItem);
        }

        // GET: OrderItems/Create
        public IActionResult Create()
        {
            ViewData["orderFK"] = new SelectList(_context.Order, "id", "id");
            ViewData["productFK"] = new SelectList(_context.Product, "id", "id");
            return View();
        }

        // POST: OrderItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,quantity,totalPrice,orderFK,productFK")] OrderItem orderItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orderItem);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["orderFK"] = new SelectList(_context.Order, "id", "id", orderItem.orderFK);
            ViewData["productFK"] = new SelectList(_context.Product, "id", "id", orderItem.productFK);
            return View(orderItem);
        }

        // GET: OrderItems/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.OrderItem == null)
            {
                return NotFound();
            }

            var orderItem = await _context.OrderItem.FindAsync(id);
            if (orderItem == null)
            {
                return NotFound();
            }
            ViewData["orderFK"] = new SelectList(_context.Order, "id", "id", orderItem.orderFK);
            ViewData["productFK"] = new SelectList(_context.Product, "id", "id", orderItem.productFK);
            return View(orderItem);
        }

        // POST: OrderItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,quantity,totalPrice,orderFK,productFK")] OrderItem orderItem)
        {
            if (id != orderItem.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orderItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OrderItemExists(orderItem.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["orderFK"] = new SelectList(_context.Order, "id", "id", orderItem.orderFK);
            ViewData["productFK"] = new SelectList(_context.Product, "id", "id", orderItem.productFK);
            return View(orderItem);
        }

        // GET: OrderItems/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.OrderItem == null)
            {
                return NotFound();
            }

            var orderItem = await _context.OrderItem
                .Include(o => o.order)
                .Include(o => o.product)
                .FirstOrDefaultAsync(m => m.id == id);
            if (orderItem == null)
            {
                return NotFound();
            }

            return View(orderItem);
        }

        // POST: OrderItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.OrderItem == null)
            {
                return Problem("Entity set 'ApplicationDbContext.OrderItem'  is null.");
            }
            var orderItem = await _context.OrderItem.FindAsync(id);
            if (orderItem != null)
            {
                _context.OrderItem.Remove(orderItem);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OrderItemExists(int id)
        {
          return (_context.OrderItem?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

DW-Final-Project/DW-Final-Project/Views/OrderItem/Create.cshtml
@model DW_Final_Project.Models.OrderItem

@{
    ViewData["Title"] = "Create";
}

<h1>Criar</h1>

<h4>Artigo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="size" class="control-label"></label>
                <select asp-for="size" class="form-control">
                    <option value="S">S</option>
                    <option value="M">M</option>
                    <option value="L">L</option>
                </select>
                <span asp-validation-for="size" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="quantity" class="control-label"></label>
                <input asp-for="quantity" min="1" class="form-control" />
                <span asp-validation-for="quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="orderFK" class="control-label"></label>
                <select asp-for="orderFK" class ="form-control" asp-items="ViewBag.orderFK"></select>
            </div>
            <div class="form-group">
                <label asp-for="productFK" class="control-label"></label>
                <select asp-for="productFK" class ="form-control" asp-items="ViewBag.productFK"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DW-Final-Project/DW-Final-Project/Views/OrderItem/Delete.cshtml
@model DW_Final_Project.Models.OrderItem

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OrderItem</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.size)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.size)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.totalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.totalPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.order)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.order.id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.product.description)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar</a>
    </form>
</div>

DW-Final-Project/DW-Final-Project/Views/OrderItem/Details.cshtml
@model DW_Final_Project.Models.OrderItem

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>OrderItem</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.size)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.size)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.totalPrice)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.totalPrice)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.order)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.order.id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.product.description)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Editar" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Voltar</a>
</div>

DW-Final-Project/DW-Final-Project/Views/OrderItem/Edit.cshtml
@model DW_Final_Project.Models.OrderItem

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Artigo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="size" class="control-label"></label>
                <select asp-for="size" class="form-control">
                    <option value="S">S</option>
                    <option value="M">M</option>
                    <option value="L">L</option>
                </select>
                <span asp-validation-for="size" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="quantity" class="control-label"></label>
                <input asp-for="quantity" class="form-control" />
                <span asp-validation-for="quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="productFK" class="control-label"></label>
                <select asp-for="productFK" class="form-control" asp-items="ViewBag.productFK"></select>
                <span asp-validation-for="productFK" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DW-Final-Project/DW-Final-Project/Views/OrderItem/Index.cshtml
@model IEnumerable<DW_Final_Project.Models.OrderItem>

@{
    ViewData["Title"] = "Index";
}

<h1>Artigos</h1>

<p>
    <a asp-controller="OrderItem" asp-action="Create">Criar</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.size)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.quantity)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.totalPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.order)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.product)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.size)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.quantity)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.totalPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.order.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.product.description)
            </td>
            <td>
                <a asp-controller="OrderItem" asp-action="Edit" asp-route-id="@item.id">Editar</a> |
                    <a asp-controller="OrderItem" asp-action="Details" asp-route-id="@item.id">Detalhes</a> |
                    <a asp-controller="OrderItem" asp-action="Delete" asp-route-id="@item.id">Apagar</a>
            </td>
        </tr>
}
    </tbody>
</table>