DW-Final-Project/DW-Final-Project/Models/Person.cs
using DW_Final_Project.Controllers;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DW_Final_Project.Models
{
	/// <summary>
	/// Dados/Informações pessoais de um utilizador
	/// </summary>
	public class Person
	{
		public Person() {
			orderList = new HashSet<Order>();
		}

		/// <summary>
		/// PK
		/// </summary>
		public int id { get; set; }

		/// <summary>
		/// Nome de um utilizador
		/// </summary>
		[Required(ErrorMessage = "O {0} é de preenchimento obrigatório")]
		[Display(Name = "Nome")]
        [RegularExpression("^[a-zçãõáéíóúA-ZÇÃÕÁÉÍÓÚ ]+$", ErrorMessage = "Tem de escrever um {0} válido")]
        [StringLength(250, ErrorMessage = "O {0} só pode ter apenas {1} caracteres")]
        public string name { get; set; }


		/// <summary>
		/// Nº de telemóvel de um utilizador
		/// </summary>
		[Required(ErrorMessage = "O {0} é de preenchimento obrigatório")]
        [Display(Name = "Telemóvel")]
        [StringLength(9, MinimumLength = 9,
         ErrorMessage = "O {0} tem de ter {1} digitos")]
        [RegularExpression("9[1236][0-9]{7}",
         ErrorMessage = "Tem de escrever um nº de {0} válido")]
        public string phoneNumber { get; set; }


		/// <summary>
		/// Morada de um utilizador
		/// </summary>
		[Required(ErrorMessage = "A {0} é de preenchimento obrigatório")]
		[Display(Name = "Morada")]
		public string address { get; set; }


		/// <summary>
		/// Código Postal de um utilizador
		/// </summary>
        [Required(ErrorMessage = "O {0} é de preenchimento obrigatório")]
        [Display(Name = "Código Postal")]
        [RegularExpression("[1-9][0-9]{3}-[0-9]{3} [A-ZÇÁÉÍÓÚ]+[A-Z -ÁÉÍÓÚÇ]*",
         ErrorMessage = "O {0} deve ser escrito no formato XXXX-XXX NOME DA TERRA")]
        public string postalCode { get; set; }


        /// <summary>
        /// Data de Nascimento de um utilizador
        /// </summary>
        [Required(ErrorMessage = "A {0} é de preenchimento obrigatório")]
        [Display(Name = "Data de Nascimento")]
        public DateTime dataNasc { get; set; }

		/// <summary>
		/// Sexo de um utilizador. M para Masculino e F para Feminino
		/// </summary>
		[Required(ErrorMessage = "O {0} é de preenchimento obrigatório")]
        [RegularExpression("[MF]{1}",
         ErrorMessage = "O {0} deve ter apenas um caracter. 'M' para Masculino e 'F' para Feminino")]
        [Display(Name = "Sexo")]
		public string gender { get; set; }

		/// <summary>
		/// Caminho de uma imagem de um utilizador
		/// </summary>
		public string? imagePath { get; set; }
		
		/// <summary>
		/// FK para userId para ASPNetUsers
		/// </summary>
		public string? userId { get; set; }

		/// <summary>
		/// Lista de ordens/compras de um utilizador
		/// </summary>
		public ICollection<Order> orderList { get; set; }


		/// <summary>
		/// DataNasc formatada para aparecer somente dd/MM/yyyy
		/// </summary>
        [NotMapped]
        public string DataNascFormatted => dataNasc.ToString("dd/MM/yyyy");
    }
}

DW-Final-Project/DW-Final-Project/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DW_Final_Project.Data;
using DW_Final_Project.Models;
using Microsoft.AspNetCore.Authorization;

namespace DW_Final_Project.Controllers {
    [Authorize]
    public class PersonController : Controller {
        private readonly ApplicationDbContext _context;

        public PersonController(ApplicationDbContext context) {
            _context = context;
        }

        // GET: Person
        public async Task<IActionResult> Index() {
            if (!User.Identity.Name.Contains("@admin.ipt.pt"))
            {
                return NotFound();
            }
            var applicationDbContext = _context.Person;
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Person/Details/5
        public async Task<IActionResult> Details(int? id) {
            if (!User.Identity.Name.Contains("@admin.ipt.pt"))
            {
                return NotFound();
            }
            if (id == null || _context.Person == null) {
                return NotFound();
            }

            var person = await _context.Person.FirstOrDefaultAsync(m => m.id == id);
            if (person == null) {
                return NotFound();
            }

            return View(person);
        }

        //// GET: Person/Create
        //public IActionResult Create() {
        //    ViewData["userFK"] = new SelectList(_context.User, "id", "email");
        //    return View();
        //}

        //// POST: Person/Create
        //// To protect from overposting attacks, enable the specific properties you want to bind to.
        //// For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public async Task<IActionResult> Create([Bind("id,name,phoneNumber,address,postalCode,dataNasc,gender,imagePath,userFK")] Person person, IFormFile imageFile) {
        //    ModelState.Remove("user");
        //    ModelState.Remove("imageFile");
        //    ModelState.Remove("imagePath");
        //    User user = await _context.User.FindAsync(person.userFK);
        //    person.user = user;
        //    if (ModelState.IsValid) {
        //        if (imageFile != null && imageFile.Length > 0) {
        //            // Gerar um nome único para o arquivo
        //            string fileName = Guid.NewGuid().ToString() + "_" + imageFile.FileName;

        //            // Caminho completo para salvar a imagem (pode ser um caminho personalizado)
        //                string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", fileName);

        //            // Salvar o arquivo no servidor
        //            using (var fileStream = new FileStream(filePath, FileMode.Create)) {
        //                await imageFile.CopyToAsync(fileStream);
        //            }

        //            // Atualizar a propriedade imagePath do objeto person com o nome do arquivo
        //            person.imagePath = fileName;
        //        } else {
        //            if (person.gender == "M") {
        //                person.imagePath = "default-m.png";
        //            } else {
        //                person.imagePath = "default-f.png";
        //            }
        //        }

        //        _context.Add(person);
        //        await _context.SaveChangesAsync();
        //        return RedirectToAction(nameof(Index));
        //    }

        //    ViewData["userFK"] = new SelectList(_context.User, "id", "email", person.userFK);
        //    return View(person);
        //}


        // GET: Person/Edit/5
        public async Task<IActionResult> Edit(int? id) {
            if (!User.Identity.Name.Contains("@admin.ipt.pt"))
            {
                return NotFound();
            }
            if (id == null || _context.Person == null) {
                return NotFound();
            }

            var person = await _context.Person.FindAsync(id);
            if (person == null) {
                return NotFound();
            }
            return View(person);
        }

        // POST: Person/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,name,phoneNumber,address,postalCode,dataNasc,gender,imagePath")] Person person, IFormFile imageFile) {
            if (!User.Identity.Name.Contains("@admin.ipt.pt"))
            {
                return NotFound();
            }
            if (id != person.id) {
                return NotFound();
            }
            ModelState.Remove("user");
            ModelState.Remove("imageFile");
            ModelState.Remove("imagePath");
            Person existingPerson = await _context.Person.FindAsync(id);

            // Copiar as propriedades atualizadas para a entidade existente
            existingPerson.id = person.id;
            existingPerson.name = person.name;
            existingPerson.phoneNumber = person.phoneNumber;
            existingPerson.address = person.address;
            existingPerson.postalCode = person.postalCode;
            existingPerson.dataNasc = person.dataNasc;
            existingPerson.gender = person.gender;

            if (ModelState.IsValid) {
                try {

                    _context.Entry(person).State = EntityState.Detached;
                    if (imageFile != null && imageFile.Length > 0)
                    {
                        // Gerar um nome único para o arquivo
                        string fileName = Guid.NewGuid().ToString() + "_" + imageFile.FileName;

                        // Caminho completo para salvar a imagem (pode ser um caminho personalizado)
                        string filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", fileName);

                        // Salvar o arquivo no servidor
                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            await imageFile.CopyToAsync(fileStream);
                        }

                        // Atualizar a propriedade imagePath do objeto person com o nome do arquivo
                        existingPerson.imagePath = fileName;
                    }
                    _context.Update(existingPerson);
                    await _context.SaveChangesAsync();
                } catch (DbUpdateConcurrencyException) {
                    if (!PersonExists(person.id)) {
                        return NotFound();
                    } else {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(person);
        }

        // GET: Person/Delete/5
        public async Task<IActionResult> Delete(int? id) {
            if (!User.Identity.Name.Contains("@admin.ipt.pt"))
            {
                return NotFound();
            }
            if (id == null || _context.Person == null) {
                return NotFound();
            }

            var person = await _context.Person
                .FirstOrDefaultAsync(m => m.id == id);
            if (person == null) {
                return NotFound();
            }

            return View(person);
        }

        // POST: Person/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id) {
            if (!User.Identity.Name.Contains("@admin.ipt.pt"))
            {
                return NotFound();
            }
            if (_context.Person == null) {
                return Problem("Entity set 'ApplicationDbContext.Person'  is null.");
            }
            var person = await _context.Person.FindAsync(id);
            if (person != null) {
                _context.Person.Remove(person);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PersonExists(int id) {
            return (_context.Person?.Any(e => e.id == id)).GetValueOrDefault();
        }
    }
}

DW-Final-Project/DW-Final-Project/Views/Person/Create.cshtml
@model DW_Final_Project.Models.Person

@{
    ViewData["Title"] = "Create";
}

<h1>Criar</h1>

<h4>Pessoa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="phoneNumber" class="control-label"></label>
                <input asp-for="phoneNumber" class="form-control" />
                <span asp-validation-for="phoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address" class="control-label"></label>
                <input asp-for="address" class="form-control" />
                <span asp-validation-for="address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="postalCode" class="control-label"></label>
                <input asp-for="postalCode" class="form-control" />
                <span asp-validation-for="postalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dataNasc" class="control-label"></label>
                <input asp-for="dataNasc" class="form-control" type="date" max="@DateTime.Now.ToString("yyyy-MM-dd")"/>
                <span asp-validation-for="dataNasc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="gender" class="control-label"></label>
                <div>
                    <label>
                        <input asp-for="gender" type="radio" value="M" /> Masculino
                    </label>
                    <label>
                        <input asp-for="gender" type="radio" value="F" /> Feminino
                    </label>
                </div>
                <span asp-validation-for="gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="imagePath" class="control-label"></label>
                <input name="imageFile" class="form-control" type="file" accept="image/*" />
                <span asp-validation-for="imagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DW-Final-Project/DW-Final-Project/Views/Person/Delete.cshtml
@model DW_Final_Project.Models.Person

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.phoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.phoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.postalCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.postalCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dataNasc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.dataNasc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.imagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.imagePath)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.userId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.userId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar</a>
    </form>
</div>

DW-Final-Project/DW-Final-Project/Views/Person/Details.cshtml
@model DW_Final_Project.Models.Person

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Person</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.phoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.phoneNumber)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.postalCode)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.postalCode)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.dataNasc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataNascFormatted)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.gender)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.gender)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.imagePath)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.imagePath)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.userId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.userId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Editar" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Voltar</a>
</div>

DW-Final-Project/DW-Final-Project/Views/Person/Edit.cshtml
@model DW_Final_Project.Models.Person

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Pessoa</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="name" class="control-label"></label>
                <input asp-for="name" class="form-control" />
                <span asp-validation-for="name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="phoneNumber" class="control-label"></label>
                <input asp-for="phoneNumber" class="form-control" />
                <span asp-validation-for="phoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="address" class="control-label"></label>
                <input asp-for="address" class="form-control" />
                <span asp-validation-for="address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="postalCode" class="control-label"></label>
                <input asp-for="postalCode" class="form-control" />
                <span asp-validation-for="postalCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="dataNasc" class="control-label"></label>
                <input asp-for="dataNasc" class="form-control" type="date" max="@DateTime.Now.ToString("yyyy-MM-dd")" />
                <span asp-validation-for="dataNasc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="gender" class="control-label"></label>
                <div>
                    <label>
                        <input asp-for="gender" type="radio" value="M" /> Masculino
                    </label>
                    <label>
                        <input asp-for="gender" type="radio" value="F" /> Feminino
                    </label>
                </div>
                <span asp-validation-for="gender" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="imagePath" class="control-label"></label>
                <input name="imageFile" class="form-control" type="file" accept="image/*"/>
                <span asp-validation-for="imagePath" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Guardar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DW-Final-Project/DW-Final-Project/Views/Person/Index.cshtml
@model IEnumerable<DW_Final_Project.Models.Person>

@{
    ViewData["Title"] = "Index";
}

<h1>Pessoas</h1>

<p>
    <a asp-area="Identity" asp-page="/Account/Register">Criar Utilizador</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.phoneNumber)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.address)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.postalCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.dataNasc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.gender)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.imagePath)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.userId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.phoneNumber)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.address)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.postalCode)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataNascFormatted)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.gender)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.imagePath)
            </td>
                <td>
                    @Html.DisplayFor(modelItem => item.userId)
                </td>
            <td>
                    <a asp-controller="Person" asp-action="Edit" asp-route-id="@item.id">Editar</a> |
                    <a asp-controller="Person" asp-action="Details" asp-route-id="@item.id">Detalhes</a> |
                    <a asp-controller="Person" asp-action="Delete" asp-route-id="@item.id">Apagar</a>
            </td>
        </tr>
}
    </tbody>
</table>